import { CardViewItem } from "@/components/shared/card-view";

export const galleryTabs = ["all", "today", "yesterday", "thisWeek", "thisMonth"] as const;

export const galleryLocations = [
  "all",
  "trigg",
  "cottesloe",
  "scarborough",
  "margaretRiver",
  "bellsBeach",
  "burleighHeads",
  "snapperRocks",
  "byronBay",
  "bondi",
  "manly",
] as const;

export const galleryTimes = ["all", "sunrise", "afternoon", "sunset"] as const;

export const gallerySorts = ["latest", "priceLow", "priceHigh"] as const;

export type GalleryTab = (typeof galleryTabs)[number];
export type GalleryLocation = (typeof galleryLocations)[number];
export type GalleryTime = (typeof galleryTimes)[number];
export type GallerySort = (typeof gallerySorts)[number];

export const galleryTabLabels: Record<GalleryTab, string> = {
  all: "All",
  today: "Today",
  yesterday: "Yesterday",
  thisWeek: "This Week",
  thisMonth: "This Month",
};

export const galleryLocationLabels: Record<GalleryLocation, string> = {
  all: "All States",
  trigg: "Trigg Beach, WA",
  cottesloe: "Cottesloe Beach, WA",
  scarborough: "Scarborough Beach, WA",
  margaretRiver: "Margaret River, WA",
  bellsBeach: "Bells Beach, VIC",
  burleighHeads: "Burleigh Heads, QLD",
  snapperRocks: "Snapper Rocks, QLD",
  byronBay: "Byron Bay, NSW",
  bondi: "Bondi Beach, NSW",
  manly: "Manly Beach, NSW",
};

export const galleryTimeLabels: Record<GalleryTime, string> = {
  all: "Any Time",
  sunrise: "Sunrise",
  afternoon: "Afternoon",
  sunset: "Sunset",
};

export const gallerySortLabels: Record<GallerySort, string> = {
  latest: "Latest",
  priceLow: "Price Low to High",
  priceHigh: "Price High to Low",
};

export type GallerySeedImage = CardViewItem & {
  tab: GalleryTab;
  locationKey: GalleryLocation;
  timeKey: GalleryTime;
  uploadedAt: string;
  priceValue: number;
};

export const gallerySeedImages: GallerySeedImage[] = [
  {
    id: 1,
    src: "/home/latest/latest1.jpg",
    alt: "Blue sky over beach",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$13.00",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "afternoon",
    uploadedAt: "2026-04-15T09:00:00.000Z",
    priceValue: 13.0,
  },
  {
    id: 2,
    src: "/home/latest/latest2.jpg",
    alt: "Clouds above ocean",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.60",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "afternoon",
    uploadedAt: "2026-04-15T07:00:00.000Z",
    priceValue: 10.6,
  },
  {
    id: 3,
    src: "/home/latest/latest3.jpg",
    alt: "Golden cloud and sea horizon",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$9.80",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-15T06:00:00.000Z",
    priceValue: 9.8,
  },
  {
    id: 4,
    src: "/home/latest/latest4.jpg",
    alt: "Deep blue wave closeup",
    userName: "John Doe",
    location: "Scarborough, WA",
    price: "$11.30",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "scarborough",
    timeKey: "afternoon",
    uploadedAt: "2026-04-15T05:00:00.000Z",
    priceValue: 11.3,
  },
  {
    id: 5,
    src: "/home/latest/latest5.jpg",
    alt: "Surfers waiting on lineup",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.20",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunrise",
    uploadedAt: "2026-04-15T04:00:00.000Z",
    priceValue: 10.2,
  },
  {
    id: 6,
    src: "/home/latest/latest6.jpg",
    alt: "Surfer resting near board",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.00",
    avatarSrc: "/home/logo.png",
    tab: "yesterday",
    locationKey: "trigg",
    timeKey: "afternoon",
    uploadedAt: "2026-04-14T09:00:00.000Z",
    priceValue: 10,
  },
  {
    id: 7,
    src: "/home/latest/latest7.jpg",
    alt: "Hand touching ocean surface",
    userName: "John Doe",
    location: "Scarborough, WA",
    price: "$9.60",
    avatarSrc: "/home/logo.png",
    tab: "yesterday",
    locationKey: "scarborough",
    timeKey: "sunset",
    uploadedAt: "2026-04-14T08:00:00.000Z",
    priceValue: 9.6,
  },
  {
    id: 8,
    src: "/home/latest/latest8.jpg",
    alt: "Surfer under bright sky",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$11.00",
    avatarSrc: "/home/logo.png",
    tab: "yesterday",
    locationKey: "trigg",
    timeKey: "sunrise",
    uploadedAt: "2026-04-14T07:00:00.000Z",
    priceValue: 11,
  },
  {
    id: 9,
    src: "/home/latest/latest1.jpg",
    alt: "Morning sky with blue tones",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.40",
    avatarSrc: "/home/logo.png",
    tab: "thisWeek",
    locationKey: "trigg",
    timeKey: "sunrise",
    uploadedAt: "2026-04-12T07:00:00.000Z",
    priceValue: 10.4,
  },
  {
    id: 10,
    src: "/home/latest/latest2.jpg",
    alt: "Soft clouds and pale blue sky",
    userName: "John Doe",
    location: "Scarborough, WA",
    price: "$12.10",
    avatarSrc: "/home/logo.png",
    tab: "thisWeek",
    locationKey: "scarborough",
    timeKey: "afternoon",
    uploadedAt: "2026-04-11T07:00:00.000Z",
    priceValue: 12.1,
  },
  {
    id: 11,
    src: "/home/latest/latest3.jpg",
    alt: "Cream clouds before sunset",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.90",
    avatarSrc: "/home/logo.png",
    tab: "thisWeek",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-10T18:00:00.000Z",
    priceValue: 8.9,
  },
  {
    id: 12,
    src: "/home/latest/latest4.jpg",
    alt: "Open ocean texture",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.90",
    avatarSrc: "/home/logo.png",
    tab: "thisWeek",
    locationKey: "trigg",
    timeKey: "afternoon",
    uploadedAt: "2026-04-09T14:00:00.000Z",
    priceValue: 10.9,
  },
  {
    id: 13,
    src: "/home/latest/latest5.jpg",
    alt: "Group waiting for clean wave",
    userName: "John Doe",
    location: "Scarborough, WA",
    price: "$9.70",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "scarborough",
    timeKey: "sunrise",
    uploadedAt: "2026-04-04T09:00:00.000Z",
    priceValue: 9.7,
  },
  {
    id: 14,
    src: "/home/latest/latest6.jpg",
    alt: "Surfer preparing on shore",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$11.40",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "afternoon",
    uploadedAt: "2026-04-03T10:00:00.000Z",
    priceValue: 11.4,
  },
  {
    id: 15,
    src: "/home/latest/latest7.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 16,
    src: "/home/latest/latest8.jpg",
    alt: "Blue sky surfing portrait",
    userName: "John Doe",
    location: "Scarborough, WA",
    price: "$10.30",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "scarborough",
    timeKey: "sunrise",
    uploadedAt: "2026-04-01T08:00:00.000Z",
    priceValue: 10.3,
  },
  {
    id: 17,
    src: "/home/latest/latest1.jpg",
    alt: "Surfers waiting on lineup",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.20",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunrise",
    uploadedAt: "2026-04-15T04:00:00.000Z",
    priceValue: 10.2,
  },
  {
    id: 18,
    src: "/home/latest/latest7.jpg",
    alt: "Surfers waiting on lineup",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.20",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunrise",
    uploadedAt: "2026-04-15T04:00:00.000Z",
    priceValue: 10.2,
  },
  {
    id: 19,
    src: "/home/latest/latest4.jpg",
    alt: "Surfers waiting on lineup",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.20",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunrise",
    uploadedAt: "2026-04-15T04:00:00.000Z",
    priceValue: 10.2,
  },
  {
    id: 20,
    src: "/home/latest/latest1.jpg",
    alt: "Surfers waiting on lineup",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$10.20",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunrise",
    uploadedAt: "2026-04-15T04:00:00.000Z",
    priceValue: 10.2,
  },
  {
    id: 21,
    src: "/home/latest/latest2.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 22,
    src: "/home/latest/latest3.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 23,
    src: "/home/latest/latest4.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 24,
    src: "/home/latest/latest5.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 25,
    src: "/home/latest/latest6.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 26,
    src: "/home/latest/latest7.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 27,
    src: "/home/latest/latest8.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "thisMonth",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 28,
    src: "/home/latest/latest1.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 29,
    src: "/home/latest/latest2.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
  {
    id: 30,
    src: "/home/latest/latest3.jpg",
    alt: "Ocean ripple closeup at dusk",
    userName: "John Doe",
    location: "Trigg Beach, WA",
    price: "$8.50",
    avatarSrc: "/home/logo.png",
    tab: "today",
    locationKey: "trigg",
    timeKey: "sunset",
    uploadedAt: "2026-04-02T16:00:00.000Z",
    priceValue: 8.5,
  },
];
