import type { PhotoModerationItem } from "@/components/dashboard/photo-moderation/photo-moderation-types";

export const photoModerationItems: PhotoModerationItem[] = [
  {
    id: 1,
    imageSrc: "/home/latest/latest1.jpg",
    images: [
      "/home/latest/latest1.jpg",
      "/home/latest/latest2.jpg",
      "/home/latest/latest3.jpg",
      "/home/latest/latest4.jpg",
      "/home/latest/latest5.jpg",
    ],
    title: "Offshore Bliss",
    priceLabel: "$45.00",
    photographer: "Saad Rayhan",
    location: "Teahupo'o, Tahiti",
    imageCount: 5,
    dateTaken: "August 14, 2023 - 08:42 AM",
    resolution: "7860 x 4370 px",
    format: "RAW / JPEG",
    size: "24.8 MB",
    submittedAt: "2026-04-03",
  },
  {
    id: 2,
    imageSrc: "/home/latest/latest2.jpg",
    images: ["/home/latest/latest2.jpg", "/home/latest/latest3.jpg", "/home/latest/latest4.jpg"],
    title: "Deep Blue Break",
    priceLabel: "$38.00",
    photographer: "Saad Rayhan",
    location: "Teahupo'o, Tahiti",
    imageCount: 3,
    dateTaken: "August 13, 2023 - 07:10 AM",
    resolution: "6720 x 4480 px",
    format: "RAW / JPEG",
    size: "21.4 MB",
    submittedAt: "2026-04-03",
  },
  {
    id: 3,
    imageSrc: "/home/latest/latest3.jpg",
    images: [
      "/home/latest/latest3.jpg",
      "/home/latest/latest4.jpg",
      "/home/latest/latest5.jpg",
      "/home/latest/latest6.jpg",
    ],
    title: "Lineup Silence",
    priceLabel: "$42.00",
    photographer: "Saad Rayhan",
    location: "Teahupo'o, Tahiti",
    imageCount: 4,
    dateTaken: "August 11, 2023 - 06:55 AM",
    resolution: "7000 x 4667 px",
    format: "RAW / JPEG",
    size: "23.1 MB",
    submittedAt: "2026-04-03",
  },
  {
    id: 4,
    imageSrc: "/home/latest/latest4.jpg",
    images: ["/home/latest/latest4.jpg", "/home/latest/latest5.jpg", "/home/latest/latest6.jpg"],
    title: "Golden Hour Drop",
    priceLabel: "$41.00",
    photographer: "Saad Rayhan",
    location: "Teahupo'o, Tahiti",
    imageCount: 3,
    dateTaken: "August 10, 2023 - 05:48 PM",
    resolution: "7680 x 5120 px",
    format: "RAW / JPEG",
    size: "22.6 MB",
    submittedAt: "2026-04-03",
  },
  {
    id: 5,
    imageSrc: "/home/latest/latest5.jpg",
    images: [
      "/home/latest/latest5.jpg",
      "/home/latest/latest6.jpg",
      "/home/latest/latest1.jpg",
      "/home/latest/latest2.jpg",
    ],
    title: "Horizon Drift",
    priceLabel: "$39.00",
    photographer: "Saad Rayhan",
    location: "Teahupo'o, Tahiti",
    imageCount: 4,
    dateTaken: "August 09, 2023 - 09:12 AM",
    resolution: "7104 x 4736 px",
    format: "RAW / JPEG",
    size: "20.9 MB",
    submittedAt: "2026-04-03",
  },
  {
    id: 6,
    imageSrc: "/home/latest/latest6.jpg",
    images: [
      "/home/latest/latest6.jpg",
      "/home/latest/latest1.jpg",
      "/home/latest/latest2.jpg",
      "/home/latest/latest3.jpg",
      "/home/latest/latest4.jpg",
    ],
    title: "Whitewater Pulse",
    priceLabel: "$44.00",
    photographer: "Saad Rayhan",
    location: "Teahupo'o, Tahiti",
    imageCount: 5,
    dateTaken: "August 08, 2023 - 11:03 AM",
    resolution: "7860 x 5240 px",
    format: "RAW / JPEG",
    size: "25.2 MB",
    submittedAt: "2026-04-03",
  },
];
