import type {
  FilterOption,
  ModeratorRow,
  ModeratorStatus,
} from "@/components/dashboard/moderator-management/moderator-management-types";

export const moderatorRows: ModeratorRow[] = [
  {
    id: 1,
    photo: "/home/latest/latest1.jpg",
    name: "Kathryn Murphy",
    email: "sara.cruz@example.com",
    phone: "(229) 555-0109",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo", "Add Location"],
    status: "Active",
  },
  {
    id: 2,
    photo: "/home/latest/latest2.jpg",
    name: "Floyd Miles",
    email: "curtis.weaver@example.com",
    phone: "(684) 555-0102",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo", "Add Location"],
    status: "Suspended",
  },
  {
    id: 3,
    photo: "/home/latest/latest3.jpg",
    name: "Kristin Watson",
    email: "alma.lawson@example.com",
    phone: "(319) 555-0115",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo"],
    status: "Suspended",
  },
  {
    id: 4,
    photo: "/home/latest/latest4.jpg",
    name: "Esther Howard",
    email: "debra.holt@example.com",
    phone: "(217) 555-0113",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo", "Add Location"],
    status: "Active",
  },
  {
    id: 5,
    photo: "/home/latest/latest5.jpg",
    name: "Ralph Edwards",
    email: "deanna.curtis@example.com",
    phone: "(405) 555-0128",
    assignedDate: "12/10/2023",
    assignedPermissions: ["All Access"],
    status: "Active",
  },
  {
    id: 6,
    photo: "/home/latest/latest6.jpg",
    name: "Courtney Henry",
    email: "jackson.graham@example.com",
    phone: "(208) 555-0112",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Add Location"],
    status: "Suspended",
  },
  {
    id: 7,
    photo: "/home/latest/latest7.jpg",
    name: "Jerome Bell",
    email: "willie.jennings@example.com",
    phone: "(308) 555-0121",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo"],
    status: "Suspended",
  },
  {
    id: 8,
    photo: "/home/latest/latest8.jpg",
    name: "Jane Cooper",
    email: "tim.jennings@example.com",
    phone: "(302) 555-0107",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo", "Add Location"],
    status: "Active",
  },
  {
    id: 9,
    photo: "/home/latest/latest9.jpg",
    name: "Albert Flores",
    email: "michael.mitc@example.com",
    phone: "(704) 555-0127",
    assignedDate: "12/10/2023",
    assignedPermissions: ["All Access"],
    status: "Active",
  },
  {
    id: 10,
    photo: "/home/latest/latest10.jpg",
    name: "Cody Fisher",
    email: "tanya.hill@example.com",
    phone: "(209) 555-0104",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo"],
    status: "Active",
  },
  {
    id: 11,
    photo: "/home/latest/latest11.jpg",
    name: "Darlene Robertson",
    email: "jessica.hanson@example.com",
    phone: "(205) 555-0100",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Add Location"],
    status: "Active",
  },
  {
    id: 12,
    photo: "/home/latest/latest12.jpg",
    name: "Savannah Nguyen",
    email: "michelle.rivera@example.com",
    phone: "(307) 555-0133",
    assignedDate: "12/10/2023",
    assignedPermissions: ["All Access"],
    status: "Active",
  },
  {
    id: 13,
    photo: "/home/latest/latest13.jpg",
    name: "Robert Fox",
    email: "felicia.reid@example.com",
    phone: "(303) 555-0105",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo", "Add Location"],
    status: "Suspended",
  },
  {
    id: 14,
    photo: "/home/latest/latest14.jpg",
    name: "Darrell Steward",
    email: "kenzi.lawson@example.com",
    phone: "(207) 555-0119",
    assignedDate: "12/10/2023",
    assignedPermissions: ["Approve Photo", "Add Location"],
    status: "Active",
  },
];

export const filterOptions: ReadonlyArray<FilterOption> = ["Recently Added", "View From Last"];

export const statusClassNameMap: Record<ModeratorStatus, string> = {
  Active: "bg-[#EDFDF3] text-[#12B76A]",
  Suspended: "bg-[#FEF3F2] text-[#F04438]",
};
