import type { LocationModerationItem } from "@/components/dashboard/locations-moderation/locations-moderation-types";

export const locationsModerationItems: LocationModerationItem[] = [
  {
    id: "byron-pass-1",
    name: "The Pass, Byron",
    region: "NSW",
    country: "Australia",
    coordinates: [-28.6434, 153.612],
    photosAvailable: 142,
    previewImage: "/home/latest/latest4.jpg",
    status: "Active",
  },
  {
    id: "snapper-rocks-1",
    name: "The Pass, Byron",
    region: "NSW",
    country: "Australia",
    coordinates: [-28.1636, 153.5482],
    photosAvailable: 136,
    previewImage: "/home/latest/latest5.jpg",
    status: "Active",
  },
  {
    id: "noosa-heads-1",
    name: "The Pass, Byron",
    region: "NSW",
    country: "Australia",
    coordinates: [-26.3918, 153.0904],
    photosAvailable: 127,
    previewImage: "/home/latest/latest6.jpg",
    status: "Active",
  },
  {
    id: "bondi-break-1",
    name: "The Pass, Byron",
    region: "NSW",
    country: "Australia",
    coordinates: [-33.8915, 151.2767],
    photosAvailable: 111,
    previewImage: "/home/latest/latest7.jpg",
    status: "Active",
  },
  {
    id: "bells-beach-1",
    name: "The Pass, Byron",
    region: "NSW",
    country: "Australia",
    coordinates: [-38.3714, 144.2838],
    photosAvailable: 95,
    previewImage: "/home/latest/latest8.jpg",
    status: "Active",
  },
  {
    id: "margaret-river-1",
    name: "The Pass, Byron",
    region: "NSW",
    country: "Australia",
    coordinates: [-33.9506, 115.0736],
    photosAvailable: 88,
    previewImage: "/home/latest/latest9.jpg",
    status: "Active",
  },
  {
    id: "gold-coast-1",
    name: "The Pass, Byron",
    region: "NSW",
    country: "Australia",
    coordinates: [-27.9944, 153.4309],
    photosAvailable: 105,
    previewImage: "/home/latest/latest10.jpg",
    status: "Active",
  },
];
