import type { FilterOption, UserPlan, UserRow, UserStatus } from "@/components/dashboard/user-management/user-management-types";

export const userRows: UserRow[] = [
  {
    id: 1,
    photo: "/home/latest/latest1.jpg",
    name: "Kathryn Murphy",
    email: "sara.cruz@example.com",
    phone: "(229) 555-0109",
    role: "User",
    contributedPhotos: null,
    plan: "Gold",
    platformCommission: null,
    purchasePhoto: 45,
    status: "Active",
  },
  {
    id: 2,
    photo: "/home/latest/latest2.jpg",
    name: "Floyd Miles",
    email: "curtis.weaver@example.com",
    phone: "(684) 555-0102",
    role: "Contributor",
    contributedPhotos: 55,
    plan: "Silver",
    platformCommission: 30,
    showCommissionSortIcon: true,
    purchasePhoto: null,
    status: "Suspended",
  },
  {
    id: 3,
    photo: "/home/latest/latest3.jpg",
    name: "Kristin Watson",
    email: "alma.lawson@example.com",
    phone: "(319) 555-0115",
    role: "User",
    contributedPhotos: null,
    plan: "Bronze",
    platformCommission: null,
    purchasePhoto: 49,
    status: "Suspended",
  },
  {
    id: 4,
    photo: "/home/latest/latest4.jpg",
    name: "Esther Howard",
    email: "debra.holt@example.com",
    phone: "(217) 555-0113",
    role: "User",
    contributedPhotos: null,
    plan: "Bronze",
    platformCommission: null,
    purchasePhoto: 48,
    status: "Active",
  },
  {
    id: 5,
    photo: "/home/latest/latest5.jpg",
    name: "Ralph Edwards",
    email: "deanna.curtis@example.com",
    phone: "(405) 555-0128",
    role: "Contributor",
    contributedPhotos: 65,
    plan: "Silver",
    platformCommission: 25,
    showCommissionSortIcon: true,
    purchasePhoto: null,
    status: "Active",
  },
  {
    id: 6,
    photo: "/home/latest/latest6.jpg",
    name: "Courtney Henry",
    email: "jackson.graham@example.com",
    phone: "(208) 555-0112",
    role: "User",
    contributedPhotos: null,
    plan: "Silver",
    platformCommission: null,
    purchasePhoto: 50,
    status: "Suspended",
  },
  {
    id: 7,
    photo: "/home/latest/latest7.jpg",
    name: "Jerome Bell",
    email: "willie.jennings@example.com",
    phone: "(308) 555-0121",
    role: "Contributor",
    contributedPhotos: 70,
    plan: "Silver",
    platformCommission: 10,
    showCommissionSortIcon: true,
    purchasePhoto: null,
    status: "Suspended",
  },
  {
    id: 8,
    photo: "/home/latest/latest8.jpg",
    name: "Jane Cooper",
    email: "tim.jennings@example.com",
    phone: "(302) 555-0107",
    role: "User",
    contributedPhotos: null,
    plan: "Gold",
    platformCommission: null,
    purchasePhoto: 47,
    status: "Active",
  },
  {
    id: 9,
    photo: "/home/latest/latest9.jpg",
    name: "Albert Flores",
    email: "michael.mitc@example.com",
    phone: "(704) 555-0127",
    role: "User",
    contributedPhotos: null,
    plan: "Gold",
    platformCommission: null,
    purchasePhoto: 51,
    status: "Active",
  },
  {
    id: 10,
    photo: "/home/latest/latest10.jpg",
    name: "Cody Fisher",
    email: "tanya.hill@example.com",
    phone: "(209) 555-0104",
    role: "User",
    contributedPhotos: null,
    plan: "Gold",
    platformCommission: null,
    purchasePhoto: 45,
    status: "Active",
  },
  {
    id: 11,
    photo: "/home/latest/latest11.jpg",
    name: "Darlene Robertson",
    email: "jessica.hanson@example.com",
    phone: "(205) 555-0100",
    role: "User",
    contributedPhotos: null,
    plan: "Gold",
    platformCommission: null,
    purchasePhoto: 52,
    status: "Active",
  },
  {
    id: 12,
    photo: "/home/latest/latest12.jpg",
    name: "Savannah Nguyen",
    email: "michelle.rivera@example.com",
    phone: "(307) 555-0133",
    role: "Contributor",
    contributedPhotos: 100,
    plan: "Bronze",
    platformCommission: 20,
    showCommissionSortIcon: true,
    purchasePhoto: null,
    status: "Active",
  },
  {
    id: 13,
    photo: "/home/latest/latest13.jpg",
    name: "Robert Fox",
    email: "felicia.reid@example.com",
    phone: "(303) 555-0105",
    role: "User",
    contributedPhotos: null,
    plan: "Bronze",
    platformCommission: null,
    purchasePhoto: 46,
    status: "Suspended",
  },
  {
    id: 14,
    photo: "/home/latest/latest14.jpg",
    name: "Darrell Steward",
    email: "kenzi.lawson@example.com",
    phone: "(207) 555-0119",
    role: "User",
    contributedPhotos: null,
    plan: "Silver",
    platformCommission: null,
    purchasePhoto: 53,
    status: "Active",
  },
];

export const filterOptions: ReadonlyArray<FilterOption> = ["All Users", "Contributors", "Users"];

export const planClassNameMap: Record<UserPlan, string> = {
  Gold: "bg-[#FBF5DD] text-[#B58212]",
  Silver: "bg-[#EEF2F6] text-[#64748B]",
  Bronze: "bg-[#FCEFEF] text-[#B07A7A]",
};

export const statusClassNameMap: Record<UserStatus, string> = {
  Active: "bg-[#EDFDF3] text-[#12B76A]",
  Suspended: "bg-[#FEF3F2] text-[#F04438]",
};
